language: ruby
rvm:
  - 1.9.2
branches:
  only:
    - travisci
before_script: 
  - chmod 777 ./config/ci/before-travis.sh
  - ./config/ci/before-travis.sh
script: 
  - cd test/core_test_app
  - bundle exec rspec spec

