language: ruby
rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - travisci
before_script: 
  - chmod 777 ./config/ci/before-travis.sh
  - ./config/ci/before-travis.sh
script: 
  - export DISPLAY=:99.0
  - cd test/core_test_app
  - bundle exec rspec spec
  - bundle exec cucumber features

